sudo: false
language: node_js
node_js:
  - 4.1
before_script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
script: npm install gift@0.10.1 && npm run-script deploy
